### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by litianjun05090** [dburckh/Media3Avi#6]
Caused by: androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArithmeticException: divide by zero
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:435)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                          at java.lang.Thread.run(Thread.java:929)
                                                                                                      Caused by: java.lang.ArithmeticException: divide by zero
                                                                                                          at com.homesoft.exo.extractor.avi.ChunkIndex.getChunkSubset(ChunkIndex.java:122)
                                                                                                          at com.homesoft.exo.extractor.avi.AudioStreamHandler.setSeekStream(AudioStreamHandler.java:62)
                                                                                                          at com.homesoft.exo.extractor.avi.AviExtractor.buildSeekMap(AviExtractor.java:153)
                                                                                                          at com.homesoft.exo.extractor.avi.AviExtractor.parseIdx1(AviExtractor.java:337)
                                                                                                          at com.homesoft.exo.extractor.avi.AviExtractor$RiffReader.read(AviExtractor.java:567)
                                                                                                          at com.homesoft.exo.extractor.avi.AviExtractor.read(AviExtractor.java:406)
                                                                                                          at androidx.media3.exoplayer.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:129)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1040)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)

**Comment by litianjun05090** [comment]
play a .avi video and has this exception.   video link :https://drive.google.com/file/d/1WwKXJ5PA9dbGUovAaKDJ_F7mzAsbkuv6/view?usp=drive_link

code `AviExtractorsFactory aviExtractorsFactory = new AviExtractorsFactory();`

**Comment by dburckh** [comment]
This file uses a FOURCC of X264, which is not in my list.  That means there is no detected video stream.  Audio only is not currently and will not likely be supported and we get a crash.  You can add in the following line to VideoFormat locally which will work-around the problem or wait for the next release, which I should have in a week or so.

    STREAM_MAP.put(0x34363258, MimeTypes.VIDEO_H264); // X264
    STREAM_MAP.put(0x34363278, MimeTypes.VIDEO_H264); // x264

**Comment by litianjun05090** [comment]
thanks !

**Comment by dburckh** [comment]
Fixed in release 2.2.1.
